version: '3.8'
services:
  db:
    image: postgres:15
    container_name: hk-cafe-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: cafe_db
    volumes:
      - db_data_cafe:/var/lib/postgresql/data

  bot:
    build: .
    container_name: hk-cafe-bot
    restart: always
    depends_on:
      - db
    environment:
      - TOKEN=${TOKEN}
      - DATABASE_URL=postgresql://admin:sua_senha_segura@db:5432/cafe_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GUILD_ID=${GUILD_ID}

volumes:
  db_data_cafe:
